"""
Standard BaseStrategy interface and signal contract for multi-strategy execution.
Enforces typed signals, lifecycle methods, parameter validation, and strict R/R constraints.
"""

from __future__ import annotations

import abc
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

try:
    from crypto_ai_trader.app.ai.regime import MarketRegime, StrategyGatingMatrix
except ImportError:
    try:
        from app.ai.regime import MarketRegime, StrategyGatingMatrix  # type: ignore
    except ImportError:
        # Fallback if standalone
        class MarketRegime(str, Enum):  # type: ignore
            STRONG_BULL = "STRONG_BULL"
            BULL = "BULL"
            SIDEWAYS = "SIDEWAYS"
            BEAR = "BEAR"
            STRONG_BEAR = "STRONG_BEAR"
            HIGH_VOLATILITY = "HIGH_VOLATILITY"
            LOW_VOLATILITY = "LOW_VOLATILITY"


class SignalAction(str, Enum):
    """Trading action generated by strategy."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    NO_TRADE = "NO_TRADE"


@dataclass
class TradeSignal:
    """
    Standard trade signal produced by any strategy implementing BaseStrategy.
    Guarantees structural completeness for risk management and order execution.
    """
    signal_id: str
    strategy_id: str
    symbol: str
    timeframe: str
    action: SignalAction
    entry_price: float
    stop_loss: float
    tp1: float
    tp2: Optional[float] = None
    tp3: Optional[float] = None
    market_regime: str = "UNKNOWN"
    technical_score: float = 0.0      # 0 to 100
    confidence: float = 0.0           # 0.0 to 1.0
    risk_reward_ratio: float = 0.0    # Reward to Risk ratio (min 1.5 default)
    reasons: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: int = 0

    def is_valid(self, min_rr: float = 1.5) -> Tuple[bool, str]:
        """Validates internal price logic and minimum risk-to-reward ratio."""
        if self.action in (SignalAction.HOLD, SignalAction.NO_TRADE):
            return True, "No active order action required"

        if self.entry_price <= 0:
            return False, f"Invalid entry price: {self.entry_price}"
        if self.stop_loss <= 0:
            return False, f"Invalid stop loss: {self.stop_loss}"
        if self.tp1 <= 0:
            return False, f"Invalid TP1: {self.tp1}"

        if self.action == SignalAction.BUY:
            if self.stop_loss >= self.entry_price:
                return False, f"BUY Stop Loss ({self.stop_loss}) must be below Entry ({self.entry_price})"
            if self.tp1 <= self.entry_price:
                return False, f"BUY TP1 ({self.tp1}) must be above Entry ({self.entry_price})"
            risk = self.entry_price - self.stop_loss
            reward = self.tp1 - self.entry_price
        elif self.action == SignalAction.SELL:
            if self.stop_loss <= self.entry_price:
                return False, f"SELL Stop Loss ({self.stop_loss}) must be above Entry ({self.entry_price})"
            if self.tp1 >= self.entry_price:
                return False, f"SELL TP1 ({self.tp1}) must be below Entry ({self.entry_price})"
            risk = self.stop_loss - self.entry_price
            reward = self.entry_price - self.tp1
        else:
            return False, f"Unknown action {self.action}"

        if risk <= 0:
            return False, "Risk distance is zero or negative"

        rr = reward / risk
        if rr < min_rr:
            return False, f"Risk-to-reward ratio {rr:.2f} is below required threshold {min_rr:.2f}"

        return True, "Signal is logically and mathematically valid"


class BaseStrategy(abc.ABC):
    """
    Abstract base class for all algorithmic trading strategies.
    Ensures a strictly uniform API:
      - generate_signal(candles, regime, context)
      - should_exit(position, current_candle, context)
      - validate_parameters(params)
      - get_required_indicators()
      - is_regime_compatible(regime)
    """

    def __init__(self, strategy_id: str, name: str, params: Optional[Dict[str, Any]] = None):
        self.strategy_id = strategy_id
        self.name = name
        self.params: Dict[str, Any] = params or {}
        self.is_enabled: bool = True
        self.validate_parameters(self.params)

    @abc.abstractmethod
    def generate_signal(
        self,
        candles: List[Dict[str, Any]],
        regime: Optional[MarketRegime] = None,
        context: Optional[Dict[str, Any]] = None
    ) -> TradeSignal:
        """
        Evaluates the latest candle stream and returns a validated TradeSignal.
        Must respect zero-lookahead bias.
        """
        pass

    @abc.abstractmethod
    def should_exit(
        self,
        position: Dict[str, Any],
        current_candle: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None
    ) -> Tuple[bool, str]:
        """
        Evaluates dynamic exit conditions (e.g. trailing stop, indicator cross, time exit).
        Returns (should_exit, reason).
        """
        pass

    @abc.abstractmethod
    def validate_parameters(self, params: Dict[str, Any]) -> bool:
        """
        Validates custom parameters for this strategy.
        Raises ValueError if invalid, returns True if valid.
        """
        pass

    @abc.abstractmethod
    def get_required_indicators(self) -> List[str]:
        """
        Returns indicator keys needed (e.g. ['ema_50', 'ema_200', 'adx_14', 'atr_14']).
        """
        pass

    def is_regime_compatible(self, regime: MarketRegime) -> bool:
        """
        Checks whether this strategy is gated out by the active market regime.
        """
        try:
            allowed = StrategyGatingMatrix.get_allowed_strategies(regime)
            return self.strategy_id in allowed
        except Exception:
            return True

    def create_no_trade_signal(
        self,
        symbol: str,
        timeframe: str,
        reason: str,
        regime: str = "UNKNOWN"
    ) -> TradeSignal:
        """Helper to generate standard NO_TRADE signal."""
        return TradeSignal(
            signal_id=f"sig_{uuid.uuid4().hex[:12]}",
            strategy_id=self.strategy_id,
            symbol=symbol,
            timeframe=timeframe,
            action=SignalAction.NO_TRADE,
            entry_price=0.0,
            stop_loss=0.0,
            tp1=0.0,
            market_regime=regime,
            technical_score=0.0,
            confidence=0.0,
            risk_reward_ratio=0.0,
            reasons=[reason]
        )
