/**
 * Phase 12: Telegram Alert & Command Bot Data & Constants
 */

export interface TelegramCommandDef {
  command: string;
  description: string;
  descriptionFa: string;
  requires2FA: boolean;
  example: string;
}

export const TELEGRAM_COMMANDS: TelegramCommandDef[] = [
  {
    command: '/status',
    description: 'Displays runtime state, active positions, pending orders, system uptime, and websocket latency.',
    descriptionFa: 'نمایش وضعیت چرخه حیات ربات، تعداد پوزیشن‌های باز، سفارش‌ها، آپ‌تایم و لتنسی.',
    requires2FA: false,
    example: '/status'
  },
  {
    command: '/balance',
    description: 'Shows total portfolio equity, available cash, peak equity, daily PnL, and current drawdown.',
    descriptionFa: 'نمایش موجودی کل، پول نقد در دسترس، سقف سرمایه، سود/زیان امروز و دراوداون جاری.',
    requires2FA: false,
    example: '/balance'
  },
  {
    command: '/positions',
    description: 'Lists all open positions with symbol, side (LONG/SHORT), leverage, entry price, mark price, unrealized PnL, and SL/TP levels.',
    descriptionFa: 'لیست کامل پوزیشن‌های باز با اهرم، قیمت ورود و لحظه‌ای، سود/زیان محقق‌نشده و سطوح SL/TP.',
    requires2FA: false,
    example: '/positions'
  },
  {
    command: '/pnl',
    description: 'Performance summary covering daily, weekly, monthly returns, win rate, and profit factor.',
    descriptionFa: 'گزارش سودآوری روزانه، هفتگی و ماهانه به همراه نرخ برد و ضریب سود.',
    requires2FA: false,
    example: '/pnl'
  },
  {
    command: '/regime',
    description: 'Returns the current AI market regime classification (Strong Bull, Sideways, High Volatility, etc.) and active strategy matrix.',
    descriptionFa: 'نمایش رژیم معاملاتی شناسایی‌شده توسط هوش مصنوعی و استراتژی‌های فعال تخصیص‌یافته.',
    requires2FA: false,
    example: '/regime'
  },
  {
    command: '/pause',
    description: 'Pauses algorithmic order execution. No new trades will be opened while existing positions remain protected.',
    descriptionFa: 'توقف موقت باز کردن معاملات جدید؛ پوزیشن‌های موجود همچنان مانیتور می‌شوند.',
    requires2FA: false,
    example: '/pause'
  },
  {
    command: '/resume',
    description: 'Resumes algorithmic trading. Requires a 6-digit confirmation token (2FA) generated by the bot to prevent accidental resumption.',
    descriptionFa: 'ادامه مجدد معاملات خودکار؛ نیازمند توکن تأیید ۶ رقمی (2FA) جهت امنیت بالا.',
    requires2FA: true,
    example: '/resume 849201'
  },
  {
    command: '/kill',
    description: 'CRITICAL EMERGENCY KILL SWITCH: Cancels all pending orders, market-flattens all positions, trips circuit breaker, and halts bot. Requires 2FA confirmation.',
    descriptionFa: 'کلید اضطراری سرخ: لغو تمامی سفارش‌ها، بستن آنی کلیه پوزیشن‌ها در مارکت و توقف کامل.',
    requires2FA: true,
    example: '/kill 395128'
  },
  {
    command: '/help',
    description: 'Displays the complete syntax reference and operational guidelines for bot management.',
    descriptionFa: 'راهنمای کامل دستورات و کلیدهای کنترل بات.',
    requires2FA: false,
    example: '/help'
  }
];

export interface Phase12TestItem {
  id: string;
  name: string;
  nameFa: string;
  category: 'Security' | 'Commands' | 'Lifecycle' | 'Alerts';
  description: string;
}

export const PHASE12_TEST_ITEMS: Phase12TestItem[] = [
  {
    id: 'test-admin-gate',
    name: 'Admin Whitelist Security Gate',
    nameFa: 'دروازه احراز هویت ادمین (Admin Whitelist)',
    category: 'Security',
    description: 'Rejects commands from non-whitelisted Telegram user IDs with an Access Denied alert.'
  },
  {
    id: 'test-rate-limit',
    name: 'Sliding-Window Rate Limiter',
    nameFa: 'محدودکننده نرخ درخواست (Rate Limiting)',
    category: 'Security',
    description: 'Prevents command flooding by throttling requests exceeding 20 commands/minute per user.'
  },
  {
    id: 'test-2fa-tokens',
    name: 'Two-Factor Confirmation Engine (2FA)',
    nameFa: 'موتور توکن‌های تأیید دو مرحله‌ای (2FA)',
    category: 'Security',
    description: 'Generates secure 6-digit single-use confirmation tokens with 60-second TTL for /kill and /resume.'
  },
  {
    id: 'test-cmd-status-regime',
    name: 'System Status & AI Regime Query',
    nameFa: 'پاسخگویی به دستورات /status و /regime',
    category: 'Commands',
    description: 'Validates formatting of uptime, positions count, pending orders, and ML regime classification.'
  },
  {
    id: 'test-cmd-balance-positions',
    name: 'Portfolio Balance & Open Positions Feed',
    nameFa: 'خوراک موجودی سبد و پوزیشن‌های باز (/balance & /positions)',
    category: 'Commands',
    description: 'Formats live equity, cash, unrealized PnL, leverage, and multi-tier SL/TP brackets in clean HTML.'
  },
  {
    id: 'test-bot-pause-resume',
    name: 'Bot Pause & 2FA Resume Workflow',
    nameFa: 'چرخه توقف و ازسرگیری با توکن ۲ مرحله‌ای',
    category: 'Lifecycle',
    description: 'Transitions bot state between RUNNING and PAUSED; ensures unpause requires validated 2FA token.'
  },
  {
    id: 'test-emergency-kill-2fa',
    name: 'Emergency Panic Kill Switch with 2FA Confirmation',
    nameFa: 'کلید اضطراری سرخ با تأیید دو مرحله‌ای',
    category: 'Lifecycle',
    description: 'Verifies /kill <token> immediately executes market-order panic closing and order cancellation.'
  },
  {
    id: 'test-alert-dispatcher',
    name: 'Real-Time Alert Dispatcher & HTML Formatter',
    nameFa: 'دیسپچر هشدارهای لحظه‌ای معامله، سود و حد ضرر',
    category: 'Alerts',
    description: 'Dispatches instant alerts for Trade Opened, TP Hit, SL Hit, Circuit Breaker, and Daily Summary.'
  }
];
